### ISSUE TITLE
ファイルが不足しています

### ISSUE THREAD

**Issue by sudahiroshi** [KOUSUKE555/soturon#1]
スタイルファイルも入れておいてください．

**Comment by KOUSUKE555** [comment]
semi.sty ではないのでしょうか．
違うのであれば，先生がおっしゃっているスタイルファイルがどのようなものなのか知らないので教えてほしいです．

**Comment by sudahiroshi** [comment]
以下のファイルが不足しています．
eclbkbox.sty
emathC.sty
itembbox.sty
itembkbx.sty
jquote.sty

**Comment by KOUSUKE555** [comment]
すみません、これらを検索してスタイルファイルとして作成すれば良いのでしょうか．

**Comment by sudahiroshi** [comment]
なるほど，CloudLaTeXの方でこれらのファイルを用意してくれていたのですね．
今，こちらの手元にあるのでDropboxに入れておきます．
Dropbox - suda - TeX
に入れておきました．
